apiVersion: v1
kind: ConfigMap
metadata:
  name: doggo-env
  labels:
    app: doggo
data:
  # Общие настройки PostgreSQL
  POSTGRES_DB: "dogs"
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"
  
  # Настройки Java-сервиса (Dog Random Service)
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/dogs"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  JAVA_SERVER_PORT: "8080"
  
  # Настройки .NET сервиса (Dog Rating Service)
  ASPNETCORE_URLS: "http://*:8081"
  ASPNETCORE_ENVIRONMENT: "Development"
  DOTNET_EF_DISABLED: ""  # Пустая строка - миграции включены
  
  # Строка подключения для .NET
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=dogs;Username=postgres;Password=postgres"
  ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=dogs;Username=postgres;Password=postgres"