apiVersion: v1
kind: ConfigMap
metadata:
  name: doggo-env
data:
  POSTGRES_DB: "dogs"
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"
  
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/dogs"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_PORT: "8080"
  
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=dogs;Username=postgres;Password=postgres"
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://*:8080"