apiVersion: apps/v1
kind: Deployment
metadata:
  name: doggo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doggo
  template:
    metadata:
      labels:
        app: doggo
    spec:
      imagePullSecrets:
      - name: nexus-secret
      containers:
      - name: doggo
        image: image-doggo-replace
        envFrom:
        - configMapRef:
            name: doggo-env
        - secretRef:
            name: doggo-secret
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: doggo
spec:
  selector:
    app: doggo
  ports:
    - port: 4000
      targetPort: 8080
  type: NodePort
