apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJob3N0Lm1pbmlrdWJlLmludGVybmFsOjUwMDAiOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJ1c2VyIiwiZW1haWwiOiJub25lQGV4YW1wbGUuY29tIiwiYXV0aCI6ImRYTmxjanAxYzJWeSJ9fX0=
kind: Secret
metadata:
  name: nexus-secret
type: kubernetes.io/dockerconfigjson
